# Generated by Django 4.2.30 on 2026-10-03 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked'), ('INVALID', 'Invalid'), ('NOT_FOUND', 'Not Found')], max_length=20)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to='credentials.credential')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verification record',
                'verbose_name_plural': 'verification records',
                'db_table': 'verification_records',
                'ordering': ['-verified_at'],
            },
        ),
    ]
