# Generated by Django 4.2.30 on 2026-09-22 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('PRIVATE_TRAINING_INSTITUTE', 'Private Training Institute'), ('COMPANY', 'Company'), ('NGO', 'NGO')], max_length=50)),
                ('official_website', models.URLField(blank=True, null=True)),
                ('official_email_domain', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('proof_document', models.FileField(upload_to='institution_proofs/')),
                ('wallet_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('trust_tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'db_table': 'institutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary_contact', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer_profiles', to='institutions.institution')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'ISSUER'}, on_delete=django.db.models.deletion.CASCADE, related_name='issuer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'issuer profile',
                'verbose_name_plural': 'issuer profiles',
                'db_table': 'issuer_profiles',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'institution')},
            },
        ),
    ]
