# Generated by Django 4.2.30 on 2026-09-25 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('action', models.CharField(choices=[('APPROVE_ISSUER', 'Approve Issuer'), ('REVOKE_ISSUER', 'Revoke Issuer'), ('ISSUE_CREDENTIAL', 'Issue Credential'), ('REVOKE_CREDENTIAL', 'Revoke Credential')], max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('gas_used', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'blockchain transaction',
                'verbose_name_plural': 'blockchain transactions',
                'db_table': 'blockchain_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
