"""
seed_demo_data — idempotent management command to create realistic end-to-end
demo data that exercises the REAL business logic (blockchain whitelist, credential
issuance, revocation).

Usage:
    py manage.py seed_demo_data            # Add-if-missing (safe to re-run)
    py manage.py seed_demo_data --reset    # Delete demo data first, then recreate
"""

import io
import uuid
from datetime import date, timedelta

from django.core.management.base import BaseCommand
from django.core.files.uploadedfile import SimpleUploadedFile
from django.utils import timezone

from apps.accounts.models import User, UserRole
from apps.students.models import StudentProfile
from apps.institutions.models import Institution, InstitutionStatus, InstitutionType, IssuerProfile
from apps.credentials.models import Credential, CredentialStatus
from apps.credentials.services import compute_document_hash, default_ipfs_service
from apps.blockchain.services import BlockchainService
from apps.blockchain.exceptions import BlockchainError, BlockchainRevertError
from apps.blockchain.models import BlockchainTransaction


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DEMO_PASSWORD = "DemoPass123!"

DEMO_USERS = [
    {"email": "admin@educhain.local", "role": UserRole.ADMIN, "is_staff": True, "is_superuser": True},
    {"email": "issuer1@stateu.edu", "role": UserRole.ISSUER},
    {"email": "issuer2@fakecert.biz", "role": UserRole.ISSUER},
    {"email": "student1@educhain.local", "role": UserRole.STUDENT},
    {"email": "recruiter1@company.com", "role": UserRole.RECRUITER},
]

DEMO_EMAILS = {u["email"] for u in DEMO_USERS}

# Predictable wallet address for initial institution registration (before
# custodial wallet generation on approval). Uses a well-known Ganache
# default account format. This will be replaced by the custodial address on
# approval; the original is preserved in `registered_wallet_address`.
INITIAL_WALLET_ISSUER1 = "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
INITIAL_WALLET_ISSUER2 = "0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0"

DEMO_CREDENTIALS = [
    {
        "credential_type": "Degree",
        "title": "Bachelor of Technology in Computer Science",
        "issue_date": date(2026, 6, 15),
        "doc_content": b"DEMO-CREDENTIAL: B.Tech Computer Science - State University of Example - 2026",
    },
    {
        "credential_type": "Certificate",
        "title": "Internship Certificate - Summer 2026",
        "issue_date": date(2026, 8, 1),
        "doc_content": b"DEMO-CREDENTIAL: Internship Certificate Summer 2026 - State University of Example",
    },
    {
        "credential_type": "Diploma",
        "title": "Post Graduate Diploma in Data Science",
        "issue_date": date(2026, 9, 20),
        "doc_content": b"DEMO-CREDENTIAL: PG Diploma Data Science - State University of Example - 2026",
    },
]

# Index (0-based) of the credential to revoke for the demo negative case
REVOKE_INDEX = 2  # "Post Graduate Diploma in Data Science"


class Command(BaseCommand):
    help = (
        "Seeds realistic demo data end-to-end using real business logic "
        "(blockchain whitelist, credential issuance/revocation). "
        "Idempotent — safe to re-run. Pass --reset to wipe demo data first."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            default=False,
            help="Delete all data created by this command before recreating it.",
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _info(self, msg):
        self.stdout.write(self.style.SUCCESS(f"  [OK] {msg}"))

    def _skip(self, msg):
        self.stdout.write(self.style.WARNING(f"  [SKIP] {msg}"))

    def _err(self, msg):
        self.stdout.write(self.style.ERROR(f"  [ERR] {msg}"))

    def _heading(self, msg):
        self.stdout.write(self.style.HTTP_INFO(f"\n{'='*60}\n  {msg}\n{'='*60}"))

    @staticmethod
    def _make_placeholder_pdf(label: str) -> bytes:
        """Generate a tiny placeholder document (plain text) for demo uploads."""
        return f"%%DEMO-PROOF-DOCUMENT%%\nInstitution Proof: {label}\nGenerated by seed_demo_data".encode("utf-8")

    # ------------------------------------------------------------------
    # Reset
    # ------------------------------------------------------------------
    def _reset(self):
        self._heading("RESET -- Removing demo data")

        # Collect demo institution IDs via issuer profiles (before deleting anything)
        issuer_emails = [u["email"] for u in DEMO_USERS if u["role"] == UserRole.ISSUER]
        demo_inst_ids = list(
            IssuerProfile.objects.filter(
                user__email__in=issuer_emails
            ).values_list("institution_id", flat=True)
        )

        # Also catch institutions by known names (fallback if profiles were already gone)
        DEMO_INSTITUTION_NAMES = ["State University of Example", "Fake Cert Institute"]
        name_ids = list(
            Institution.objects.filter(name__in=DEMO_INSTITUTION_NAMES)
            .values_list("id", flat=True)
        )
        demo_inst_ids = list(set(demo_inst_ids) | set(name_ids))

        # Credentials from demo institutions
        cred_count, _ = Credential.objects.filter(institution_id__in=demo_inst_ids).delete()
        self._info(f"Deleted {cred_count} credential records")

        # Blockchain transactions related to demo institutions
        tx_count, _ = BlockchainTransaction.objects.filter(related_object_id__in=demo_inst_ids).delete()
        self._info(f"Deleted {tx_count} blockchain transaction records (institution-related)")

        # IssuerProfiles
        ip_count, _ = IssuerProfile.objects.filter(
            user__email__in=issuer_emails
        ).delete()
        self._info(f"Deleted {ip_count} issuer profile records")

        # Institutions
        inst_count, _ = Institution.objects.filter(id__in=demo_inst_ids).delete()
        self._info(f"Deleted {inst_count} institution records")

        # StudentProfiles
        sp_count, _ = StudentProfile.objects.filter(user__email__in=DEMO_EMAILS).delete()
        self._info(f"Deleted {sp_count} student profile records")

        # Users
        u_count, _ = User.objects.filter(email__in=DEMO_EMAILS).delete()
        self._info(f"Deleted {u_count} user records")

    # ------------------------------------------------------------------
    # Step 1: Users
    # ------------------------------------------------------------------
    def _create_users(self) -> dict:
        self._heading("Step 1 — Users")
        users = {}
        for spec in DEMO_USERS:
            email = spec["email"]
            existing = User.objects.filter(email__iexact=email).first()
            if existing:
                self._skip(f"User {email} already exists (id={existing.id})")
                users[email] = existing
                continue

            extra = {}
            if spec.get("is_staff"):
                extra["is_staff"] = True
            if spec.get("is_superuser"):
                extra["is_superuser"] = True

            if spec["role"] == UserRole.ADMIN:
                user = User.objects.create_superuser(
                    email=email,
                    password=DEMO_PASSWORD,
                    role=UserRole.ADMIN,
                    **extra,
                )
            else:
                user = User.objects.create_user(
                    email=email,
                    password=DEMO_PASSWORD,
                    role=spec["role"],
                    **extra,
                )
            self._info(f"Created user {email} (role={spec['role']}, id={user.id})")
            users[email] = user
        return users

    # ------------------------------------------------------------------
    # Step 2: StudentProfile
    # ------------------------------------------------------------------
    def _create_student_profile(self, student_user: User) -> StudentProfile:
        self._heading("Step 2 — Student Profile")
        existing = StudentProfile.objects.filter(user=student_user).first()
        if existing:
            self._skip(f"StudentProfile for {student_user.email} already exists (id={existing.id})")
            return existing

        profile = StudentProfile.objects.create(
            user=student_user,
            full_name="Alice Student",
            roll_number="STU-2026-001",
            date_of_birth=date(2004, 3, 15),
        )
        self._info(f"Created StudentProfile: {profile.full_name} (id={profile.id})")
        return profile

    # ------------------------------------------------------------------
    # Step 3: Institution + IssuerProfile for issuer1
    # ------------------------------------------------------------------
    def _create_institution_issuer1(self, issuer_user: User) -> Institution:
        self._heading("Step 3 — Institution for issuer1 (State University of Example)")
        existing_ip = IssuerProfile.objects.filter(user=issuer_user).select_related("institution").first()
        if existing_ip:
            self._skip(
                f"IssuerProfile for {issuer_user.email} already exists "
                f"→ Institution '{existing_ip.institution.name}' (status={existing_ip.institution.status})"
            )
            return existing_ip.institution

        proof_bytes = self._make_placeholder_pdf("State University of Example")
        proof_file = SimpleUploadedFile(
            "state_university_proof.pdf",
            proof_bytes,
            content_type="application/pdf",
        )

        institution = Institution.objects.create(
            name="State University of Example",
            institution_type=InstitutionType.UNIVERSITY,
            official_website="https://stateu.edu",
            official_email_domain="stateu.edu",
            registration_number="AICTE-U-2019-04521",
            gst_number="29AABCU9603R1ZP",
            proof_document=proof_file,
            wallet_address=INITIAL_WALLET_ISSUER1,
            status=InstitutionStatus.PENDING,
        )
        IssuerProfile.objects.create(
            user=issuer_user,
            institution=institution,
            is_primary_contact=True,
        )
        self._info(
            f"Created Institution '{institution.name}' (id={institution.id}) + IssuerProfile"
        )
        return institution

    # ------------------------------------------------------------------
    # Step 4: Institution + IssuerProfile for issuer2 (stays PENDING)
    # ------------------------------------------------------------------
    def _create_institution_issuer2(self, issuer_user: User) -> Institution:
        self._heading("Step 4 — Institution for issuer2 (Fake Cert Institute — stays PENDING)")
        existing_ip = IssuerProfile.objects.filter(user=issuer_user).select_related("institution").first()
        if existing_ip:
            self._skip(
                f"IssuerProfile for {issuer_user.email} already exists "
                f"→ Institution '{existing_ip.institution.name}' (status={existing_ip.institution.status})"
            )
            return existing_ip.institution

        proof_bytes = self._make_placeholder_pdf("Fake Cert Institute")
        proof_file = SimpleUploadedFile(
            "fakecert_proof.pdf",
            proof_bytes,
            content_type="application/pdf",
        )

        institution = Institution.objects.create(
            name="Fake Cert Institute",
            institution_type=InstitutionType.PRIVATE_TRAINING_INSTITUTE,
            official_website="https://fakecert.biz",
            official_email_domain="fakecert.biz",
            registration_number="UNREG-2025-99999",
            gst_number="99ZZZZZ0000Z0ZZ",
            proof_document=proof_file,
            wallet_address=INITIAL_WALLET_ISSUER2,
            status=InstitutionStatus.PENDING,
        )
        IssuerProfile.objects.create(
            user=issuer_user,
            institution=institution,
            is_primary_contact=True,
        )
        self._info(
            f"Created Institution '{institution.name}' (id={institution.id}) + IssuerProfile  [PENDING — fraud-prevention demo]"
        )
        return institution

    # ------------------------------------------------------------------
    # Step 5: Approve issuer1 (real blockchain call)
    # ------------------------------------------------------------------
    def _approve_institution(self, institution: Institution, admin_user: User) -> bool:
        self._heading("Step 5 — Approve issuer1 institution (on-chain whitelist)")

        if institution.status == InstitutionStatus.APPROVED:
            self._skip(
                f"Institution '{institution.name}' is already APPROVED "
                f"(wallet={institution.wallet_address})"
            )
            return True

        if institution.status != InstitutionStatus.PENDING:
            self._err(
                f"Institution '{institution.name}' has status={institution.status}, "
                f"cannot approve (expected PENDING)."
            )
            return False

        # Replicate the exact code path from ApproveInstitutionView.post()
        # 1. Generate custodial wallet if not already present
        if not institution.encrypted_private_key:
            institution.generate_custodial_wallet()

        # 2. On-chain whitelist call
        trust_tier = 1
        try:
            tx_hash = BlockchainService.approve_issuer(
                wallet_address=institution.wallet_address,
                name=institution.name,
                trust_tier=trust_tier,
                related_object_id=institution.id,
            )
        except (BlockchainError, BlockchainRevertError) as exc:
            self._err(f"Blockchain call failed: {exc}")
            self._err(
                "Please ensure Ganache is running (npx ganache --port 7545) "
                "with a deployed CredentialPlatform contract, then re-run:\n"
                "    py manage.py seed_demo_data"
            )
            return False
        except Exception as exc:
            self._err(f"Unexpected error during approval: {exc}")
            self._err(
                "Please start Ganache and re-run: py manage.py seed_demo_data"
            )
            return False

        # 3. Update DB status (mirrors ApproveInstitutionView)
        institution.status = InstitutionStatus.APPROVED
        institution.trust_tier = trust_tier
        institution.reviewed_by = admin_user
        institution.reviewed_at = timezone.now()
        institution.rejection_reason = None
        institution.save()

        self._info(
            f"Institution '{institution.name}' APPROVED on-chain "
            f"(tx={tx_hash}, custodial_wallet={institution.wallet_address})"
        )

        # 3b. Fund the custodial wallet so it can pay gas for credential issuance.
        # On a local Ganache the freshly generated custodial wallet has 0 ETH.
        self._fund_custodial_wallet(institution)

        return True

    def _fund_custodial_wallet(self, institution: Institution):
        """Send 1 ETH from the platform admin wallet to the custodial wallet so it can issue credentials."""
        try:
            w3 = BlockchainService.get_web3()
            admin_pk = BlockchainService.get_admin_private_key()
            admin_account = w3.eth.account.from_key(admin_pk)
            custodial_addr = w3.to_checksum_address(institution.wallet_address)

            balance = w3.eth.get_balance(custodial_addr)
            one_ether = w3.to_wei(1, 'ether')

            if balance >= one_ether:
                self._skip(
                    f"Custodial wallet {custodial_addr} already has "
                    f"{w3.from_wei(balance, 'ether')} ETH -- skipping funding"
                )
                return

            nonce = w3.eth.get_transaction_count(admin_account.address, 'pending')
            tx = {
                'to': custodial_addr,
                'value': one_ether,
                'gas': 21000,
                'gasPrice': w3.eth.gas_price,
                'nonce': nonce,
                'chainId': BlockchainService.get_chain_id(),
            }
            signed = w3.eth.account.sign_transaction(tx, private_key=admin_pk)
            raw = getattr(signed, 'raw_transaction', None) or getattr(signed, 'rawTransaction', None)
            tx_hash_bytes = w3.eth.send_raw_transaction(raw)
            w3.eth.wait_for_transaction_receipt(tx_hash_bytes, timeout=15)

            self._info(
                f"Funded custodial wallet {custodial_addr} with 1 ETH "
                f"(tx={w3.to_hex(tx_hash_bytes)})"
            )
        except Exception as exc:
            self._err(f"Failed to fund custodial wallet: {exc}")
            self._err("Credential issuance will likely fail due to insufficient gas.")

    # ------------------------------------------------------------------
    # Step 6: Issue credentials (real blockchain call)
    # ------------------------------------------------------------------
    def _issue_credentials(self, institution: Institution, student_profile: StudentProfile) -> list:
        self._heading("Step 6 — Issue credentials from issuer1 to student1")
        issued = []

        for idx, spec in enumerate(DEMO_CREDENTIALS):
            doc_content = spec["doc_content"]
            document_hash = compute_document_hash(doc_content)

            # Idempotency: check if credential with this document_hash already exists
            existing = Credential.objects.filter(document_hash__iexact=document_hash).first()
            if existing:
                self._skip(
                    f"Credential '{spec['title']}' already exists "
                    f"(id={existing.id}, status={existing.status})"
                )
                issued.append(existing)
                continue

            # Step 1: IPFS upload
            ipfs_cid = default_ipfs_service.upload_document(doc_content, filename=f"demo_cred_{idx}.pdf")

            # Step 2: Create DB record in PENDING status
            credential = Credential.objects.create(
                student=student_profile,
                institution=institution,
                credential_type=spec["credential_type"],
                title=spec["title"],
                issue_date=spec["issue_date"],
                document_hash=document_hash,
                ipfs_cid=ipfs_cid,
                status=CredentialStatus.PENDING,
            )

            # Step 3: On-chain issuance
            try:
                tx_hash = BlockchainService.issue_credential(
                    credential_id=credential.id,
                    document_hash=document_hash,
                    ipfs_cid=ipfs_cid,
                    issuer_wallet_address=institution.wallet_address,
                    related_object_id=credential.id,
                )
            except (BlockchainError, BlockchainRevertError) as exc:
                self._err(f"Blockchain issuance failed for '{spec['title']}': {exc}")
                self._err("Credential remains PENDING — fix blockchain and re-run.")
                issued.append(credential)
                continue

            # Step 4: Mark ACTIVE
            credential.status = CredentialStatus.ACTIVE
            credential.tx_hash = tx_hash
            credential.save(update_fields=["status", "tx_hash", "updated_at"])

            self._info(
                f"Issued credential '{spec['title']}' "
                f"(id={credential.id}, tx={tx_hash})"
            )
            issued.append(credential)

        return issued

    # ------------------------------------------------------------------
    # Step 7: Revoke one credential (real blockchain call)
    # ------------------------------------------------------------------
    def _revoke_credential(self, credentials: list, institution: Institution):
        self._heading("Step 7 — Revoke one credential for demo verification")

        if REVOKE_INDEX >= len(credentials):
            self._err(f"Revoke index {REVOKE_INDEX} out of range ({len(credentials)} credentials)")
            return

        target = credentials[REVOKE_INDEX]

        if target.status == CredentialStatus.REVOKED:
            self._skip(
                f"Credential '{target.title}' is already REVOKED (id={target.id})"
            )
            return

        if target.status != CredentialStatus.ACTIVE:
            self._err(
                f"Credential '{target.title}' has status={target.status}, "
                f"cannot revoke (expected ACTIVE)."
            )
            return

        try:
            tx_hash = BlockchainService.revoke_credential(
                credential_id=target.id,
                issuer_wallet_address=institution.wallet_address,
                related_object_id=target.id,
            )
        except (BlockchainError, BlockchainRevertError) as exc:
            self._err(f"Blockchain revocation failed: {exc}")
            return

        target.status = CredentialStatus.REVOKED
        target.tx_hash = tx_hash
        target.revoked_at = timezone.now()
        target.revocation_reason = "Demo revocation — credential voided for testing purposes"
        target.save(update_fields=["status", "tx_hash", "revoked_at", "revocation_reason", "updated_at"])

        self._info(
            f"Revoked credential '{target.title}' (id={target.id}, tx={tx_hash})"
        )

    # ------------------------------------------------------------------
    # Summary table
    # ------------------------------------------------------------------
    def _print_summary(self, users: dict, credentials: list):
        self._heading("DEMO DATA SUMMARY")

        # Users table
        self.stdout.write("\n  USERS:")
        self.stdout.write(f"  {'Email':<30} {'Role':<10} {'Password'}")
        self.stdout.write(f"  {'-'*30} {'-'*10} {'-'*15}")
        for spec in DEMO_USERS:
            email = spec["email"]
            self.stdout.write(f"  {email:<30} {spec['role']:<10} {DEMO_PASSWORD}")

        # Institutions table
        self.stdout.write("\n  INSTITUTIONS:")
        self.stdout.write(f"  {'Name':<40} {'Status':<12} {'Wallet Address'}")
        self.stdout.write(f"  {'-'*40} {'-'*12} {'-'*42}")
        for inst in Institution.objects.filter(
            issuer_profiles__user__email__in=[u["email"] for u in DEMO_USERS if u["role"] == UserRole.ISSUER]
        ).distinct():
            self.stdout.write(f"  {inst.name:<40} {inst.status:<12} {inst.wallet_address}")

        # Credentials table
        self.stdout.write("\n  CREDENTIALS:")
        self.stdout.write(f"  {'ID':<38} {'Title':<50} {'Status'}")
        self.stdout.write(f"  {'-'*38} {'-'*50} {'-'*10}")
        for cred in credentials:
            cred.refresh_from_db()
            self.stdout.write(f"  {str(cred.id):<38} {cred.title:<50} {cred.status}")

        # Password reminder
        self.stdout.write(self.style.NOTICE(
            f"\n  +{'='*58}+\n"
            f"  |  SHARED DEMO PASSWORD:  {DEMO_PASSWORD:<32}|\n"
            f"  +{'='*58}+\n"
        ))

    # ------------------------------------------------------------------
    # Main entry
    # ------------------------------------------------------------------
    def handle(self, *args, **options):
        self.stdout.write(self.style.HTTP_INFO("\n" + "=" * 60))
        self.stdout.write(self.style.HTTP_INFO("  EDUCHAIN -- seed_demo_data"))
        self.stdout.write(self.style.HTTP_INFO("=" * 60))

        if options["reset"]:
            self._reset()

        # Step 1: Users
        users = self._create_users()

        # Step 2: Student profile
        student_user = users["student1@educhain.local"]
        student_profile = self._create_student_profile(student_user)

        # Step 3: Institution for issuer1
        issuer1_user = users["issuer1@stateu.edu"]
        institution1 = self._create_institution_issuer1(issuer1_user)

        # Step 4: Institution for issuer2 (stays PENDING)
        issuer2_user = users["issuer2@fakecert.biz"]
        institution2 = self._create_institution_issuer2(issuer2_user)

        # Step 5: Approve issuer1
        admin_user = users["admin@educhain.local"]
        approved = self._approve_institution(institution1, admin_user)
        if not approved:
            self.stdout.write(self.style.ERROR(
                "\n  [!] Stopping early -- blockchain approval failed.\n"
                "  Start Ganache and re-run:  py manage.py seed_demo_data\n"
            ))
            return

        # Step 6: Issue credentials
        credentials = self._issue_credentials(institution1, student_profile)

        # Step 7: Revoke one credential
        if credentials:
            self._revoke_credential(credentials, institution1)

        # Summary
        self._print_summary(users, credentials)

        self.stdout.write(self.style.SUCCESS("\n  [DONE] seed_demo_data complete!\n"))
