# Generated by Django 4.2.30 on 2026-09-26 07:50
# Manually updated: removed StudentProfile (moved to apps/students/migrations/0001_initial.py)
# and updated Credential.student FK to reference students.StudentProfile.

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),  # StudentProfile now lives in apps.students
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('document_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('ipfs_cid', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_credentials', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'credential',
                'verbose_name_plural': 'credentials',
                'db_table': 'credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('visible_fields', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='credentials.credential')),
            ],
            options={
                'verbose_name': 'credential share',
                'verbose_name_plural': 'credential shares',
                'db_table': 'credential_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='credential',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='students.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['student'], name='credentials_student_5be2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['institution'], name='credentials_institu_0a102d_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['status'], name='credentials_status_ab5a76_idx'),
        ),
    ]
